### ISSUE TITLE
All intents are returned as endConversation: true

### ISSUE THREAD

**Issue by zerowon01** [yoichiro/dialogflow-query-checker#19] opened 2018-03-02 23:11 UTC
Minor thing, but it appears that for whatever reason, all tests are evaluating to endConversation: true despite the implementation of the particular intent in DialogFlow.  I tried turning on/off the "set this intent as end of conversation," but in either the tests are always expecting endConversation: true to achieve a passing result.

**Comment by yoichiro** [comment] 2018-03-05 00:52
@zerowon01 Hmm... I have a question. Which is your situation?

1. The Dialogflow your project always returns a value as `endConversation: true`. Therefore, if you define each test-case with `endConversation: false`, but the test-case is failed.
1. The Dialogflow your project returns a value as 'endConversation: false'. However, all test-cases for this tool have a definition as `endConversation: true`. Therefore, some test-cases are failed.

**Comment by yoichiro** [comment] 2018-03-05 01:32
@zerowon01 Ok, I understand your situation. I will investigate the cause, just a moment. Thank you for the reporting.

**Comment by yoichiro** [comment] 2018-03-05 03:14
@zerowon01 Hmm... I can't reproduce the issue you reported. Could you send me your yaml file and the output log? At this time, you can include more detail information with `-d` option at running this tool.

**Comment by zerowon01** [comment] 2018-03-05 03:56
Git didn't allow yaml or yml so I renamed it with txt extension.
This is the test file that I'm currently working on. As you will see ALL of my test definitions include endConversation: true. Otherwise they fail to test as expected (endConversation: false). I'm using v1 of the DialogFlow API if that makes any differnce...

[test.txt](https://github.com/yoichiro/dialogflow-query-checker/files/1779452/test.txt)

**Comment by yoichiro** [comment] 2018-03-05 03:56
> Test evaluation returned: "Expected: false \n Actual: true"

At least, the `Actual: true` means that the Dialogflow returned the following response:

```text
"expect_user_response": false,
```

That is, your mention "My agent: has (0) intents where endConversation: true" is not correct, I think. For example, you select the "end conversation" checkbox on the Dialogflow intent form, but the Dialogflow returns `"expect_user_response": false,` if you use `app.tell()` function in your fulfillment logic.

@zerowon01 I will be able to know the behavior under your situation by your yaml file and the output log.

**Comment by yoichiro** [comment] 2018-03-05 04:03
@zerowon01 Oh, sorry. I have a mistake. Is your issue the following, right?

* You defined some test-cases with `endConversation: true`.
* You ran the tests, but these test-cases output the log `Expected: false,` for endConversation checking. The correct behavior is `Expected: true, `.

**Comment by yoichiro** [comment] 2018-03-05 04:11
@zerowon01 I found an issue in your file. I guess that you defined two test cases of "#Default fallback intent?" and "#Who are you?". However, the definition has only one test case, because there is not `-` character before the 2nd `condition:`. In YAML, each item in an array must start `-` character.

**Comment by zerowon01** [comment] 2018-03-05 04:20
I'm saying the problem is that any test I write I MUST use endConversation: true to pass, despite the actual value in DialogFlow. Maybe I should put in an API reply snippet (I suppose DialogFlow could be "broken.").. API output added below. (While doing that I noticed there is no mention of endConversation in the API response..... Perhaps I'm not understanding something here in the DialogFlow spec...?)

Anyway, if I assume that the test code works correctly, this would mean that all my intents ARE in fact defined as endConversation: true. I know this is NOT true. So my assumption is that the test code is malfunctioning in some way so it APPEARS that my defined intents are defined as endConversation: true.

API reply for my Default Fallback Intent:
`
{
    "id": "xxxxxxxxxxx",
    "name": "Default Welcome Intent",
    "auto": true,
    "contexts": [],
    "responses": [
        {
            "resetContexts": false,
            "action": "input.welcome",
            "affectedContexts": [],
            "parameters": [],
            "messages": [
                {
                    "type": 0,
                    "speech": [
                        "Hi!",
                        "Hello!",
                        "Good day!",
                        "Greetings!"
                    ]
                }
            ],
            "defaultResponsePlatforms": {},
            "speech": []
        }
    ],
    "priority": 500000,
    "webhookUsed": false,
    "webhookForSlotFilling": false,
    "fallbackIntent": false,
    "events": [
        {
            "name": "WELCOME"
        }
    ],
    "userSays": [],
    "followUpIntents": [],
    "templates": []
}
`

**Comment by yoichiro** [comment] 2018-03-05 04:23
@zerowon01 Sorry, this issue is about `endConversion`, but it is `YAML format`, I think. Please see https://github.com/yoichiro/dialogflow-query-checker/issues/19#issuecomment-370305019. And, I just updated the sample code in the README.md file. Could you check your configuration YAML file?

**Comment by zerowon01** [comment] 2018-03-05 04:40
@yoichiro Fixing the YAML syntax did solve  #21. However the endConversation: true issue in this ticket, is still being observed. 
For this issue, the test results are VERY explicit. Expected: false, Actual: true. Despite my intent very clearly being of the condition "endConversation: false" per the DialogFlow console.

**Comment by yoichiro** [comment] 2018-03-05 04:45
@zerowon01 Hmm... Ok, give me a few hours to further investigate this issue.

**Comment by zerowon01** [comment] 2018-03-05 04:49
@yoichiro Thanks in advance.

**Comment by yoichiro** [comment] 2018-03-05 04:50
@zerowon01 Finally, I could reproduce your situation on my environment. I will fix this issue. I'm sorry for my confused comments.

**Comment by yoichiro** [comment] 2018-03-05 05:47
@zerowon01 I have just released a new version 1.11.1 https://github.com/yoichiro/dialogflow-query-checker/releases/tag/1.11.1 including a code to fix this issue. Could you test your yaml file using this version?

**Comment by yoichiro** [comment] 2018-03-05 06:52
@zerowon01 I cannot access your Dialogflow agent, therefore, I cannot understand the details. You can output the detail log with `-d` option. For example, `dialogflow-query-checker run -d ./foo.yml`. I may know your situation, if you send me the log output.

**Comment by zerowon01** [comment] 2018-03-05 07:44
@yoichiro, please find below:

**Here is the condition/expect pair**

      condition:
        query: "Let's stop talking about this topic now" 
      expect:
        action: "misc.end.conversation"
        intentName: "misc.end.conversation"
        speeches:
          - "Yeah, I've got better things to do anyway."
        endConversation: true


**Here is the debugging output as requested:**

The debug mode is on
The count of retrying: 0
Running query tests for Dialogflow.
[Start] Query: Let's stop talking about this topic now

<Request body> {
  "lang": "en",
  "originalRequest": {
    "source": "google",
    "data": {
      "user": {
        "locale": "en-US"
      }
    }
  },
  "query": "Let's stop talking about this topic now",
  "event": {},
  "sessionId": "03104e56-3e46-4a32-9bda-4e0a175d57a4"
}
<Response Status> 200 OK
<Response body> {
  "id": "097a3b6d-137c-4171-81ac-1cf05759f5c3",
  "timestamp": "2018-03-05T07:39:09.286Z",
  "lang": "en",
  "result": {
    "source": "agent",
    "resolvedQuery": "Let's stop talking about this topic now",
    "action": "misc.end.conversation",
    "actionIncomplete": false,
    "parameters": {},
    "contexts": [],
    "metadata": {
      "intentId": "6f6ed5a4-5147-4b7a-a2fe-1c82531aac14",
      "webhookUsed": "false",
      "webhookForSlotFillingUsed": "false",
      "endConversation": true,
      "intentName": "misc.end.conversation"
    },
    "fulfillment": {
      "speech": "Yeah, I've got better things to do anyway....",
      "messages": [
        {
          "type": 0,
          "speech": "Yeah, I've got better things to do anyway...."
        }
      ]
    },
    "score": 0.7699999809265137
  },
  "status": {
    "code": 200,
    "errorType": "success",
    "webhookTimedOut": false
  },
  "sessionId": "03104e56-3e46-4a32-9bda-4e0a175d57a4"
}
....F

**Comment by yoichiro** [comment] 2018-03-05 08:53
@zerowon01 Thank you for posting your log. As the result, I just notice that it is hard to fix this issue. At least, I don't have any good idea to fix this.

In this current version, this tool checks whether the conversation was ended by "data.google. expectUserResponse" response value. As my testing, when a fulfillment was used, the expectUserResponse value was returned. However, when a fulfillment was not used (that is, the dialogflow returned the result directly), the expectUserResponse value was NOT returned. I guess that your situation is the 2nd. This means that this tool cannot recognize whether the conversation is ended or not.

Probably, this reason may be that this tool cannot emulate a request as same as AoG, I guess. That is, I need to find an idea that the Dialogflow always returns the expectUserResponse value.

**Comment by yoichiro** [comment] 2018-03-05 08:57
@zerowon01 Anyway, I will release a new version which the endConversation checking is disabled.

**Comment by zerowon01** [comment] 2018-03-05 09:05
@yoichiro Yeah, I believe the endConversation logic is specific to the Google Assistant / Actions on Google implementation. Anyway, for my case, being able to circumvent the check is perfect, as it's not something I would really test for. Thanks again for your effort.

**Comment by yoichiro** [comment] 2018-03-05 09:43
I have just released the new version 1.12.0 which the endConversation check feature deleted: https://github.com/yoichiro/dialogflow-query-checker/releases/tag/1.12.0

@zerowon01 Thank you for the great reporting! I close this issue.

**Closed by yoichiro** 2018-03-05 09:43 UTC
Labels: bug
